### ISSUE TITLE
[bug]現在の QIita では class が違うため動作しない

### ISSUE THREAD

**Issue by MikuroXina** [ia15076/qiita-scroll-sync#2]
現在の Qiita では DOM 要素の class 指定が変わっているため, スクリプト内での `querySelector` 呼び出しが `null` を返すために動作しません.

当該部分を直そうとしてみましたが, `querySelector` 部分を直すだけでは以下の問題も発生して改善しなかったため PR ではなく Issue として立てます.

- Markdown プレビューが読み込まれるタイミングが `DOMContentLoaded` より後のタイミングになったため, 編集画面を開いてこのスクリプトが読み込まれてから一旦再読み込みをしない限り, プレビュー側の要素を取得できずにスクリプトが動作しない.
- 最初に見出しが存在する場合に y 座標側は `[0, 0, ...]` と始まらないためプレビュー側の見出しが 1 つずれる.

`querySelector` の部分のみの修正を PR として作成した後に, 上記を別々の issue へと分けようかと考えています. どういたしましょうか?

**Comment by fukuchancat** [comment]
@MikuroXina さん、Issueの報告ありがとうございます。

確かに現在のQiitaでは動作しないですね…こちらでも軽く直せないか見てみたのですがそれなりに大きな変更が必要になりそうです。

それではご提案の通りに部分修正PRの作成と別々のIssue立てをよろしくお願いできますでしょうか。

**Comment by MikuroXina** [comment]
@ia15076 , Issue を立てておきました. 修正 PR に関しては先に #3 を作っているのでそちらのマージを待ちます.

**Comment by fukuchancat** [comment]
@MikuroXina さん、申し訳ありませんが以下の2つの理由から #3 をrejectさせてください。

一つに、

> Markdown プレビューが読み込まれるタイミングが DOMContentLoaded より後のタイミングになったため, 編集画面を開いてこのスクリプトが読み込まれてから一旦再読み込みをしない限り, プレビュー側の要素を取得できずにスクリプトが動作しない.

この点についてこちらでもclass指定を変えて再現できるか改めて試してみたところ、プレビューが読み込まれるタイミングでMutationObserverがそれを正常に検知して動作したために、動かない状況を再現できませんでした。したがって問題の原因が元のコードにあるのかリファクタリングのどこかにあるのかを切り分けて考えたいと思っています。

もう一つに、
リポジトリの管理者(私)が現在のところリファクタリングを必要としていないことです。

問題を再現するための作業の過程で原因はだいたい分かりましたので、現状のバグの解消については立てて頂いたIssue #4 #5 を使う形でこちらで取り組ませてもらおうと考えています。
どうぞよろしくお願いいたします。
