### ISSUE TITLE
[bug]多くの状況で動作しない

### ISSUE THREAD

**Issue by MikuroXina** [ia15076/qiita-scroll-sync#4]
Markdown プレビューが読み込まれるタイミングが `DOMContentLoaded` より後の非同期なタイミングになりました.

この変更の影響で, 編集画面を開いてこのスクリプトが読み込まれてもプレビュー側の要素を取得できず正常に動作しません. 一旦再読み込みをすれば, タイミングによっては動作します.

なんらかの手段でプレビューの読み込みを待つように修正する必要があります.

**Comment by fukuchancat** [comment]
Qiitaの仕様変更への対応後、再現することができませんでした(従前からプレビュー側の要素を使う計算はDOMContentLoadedイベント時ではなくMutationObserverがプレビューの読み込みを検知したときに行われている)。

動作環境の違いによるものかもしれませんので、今後も同様の問題が再現される場合にはすみませんがもう一度Issue立てをよろしくお願いいたします。
