### ISSUE TITLE
[bug]スクロール同期がずれる

### ISSUE THREAD

**Issue by MikuroXina** [ia15076/qiita-scroll-sync#5]
編集中の記事の最初に見出しが存在する場合において, プレビュー側の見出しが 1 つずれるという状況が発生しました.

調査したところ, 最初に見出しが存在する場合に x 座標側が `[0, 0, ...]` と始まるようになっているにもかかわらず, y 座標側は `[0, 0, ...]` と始まらないため座標の要素の対応がおかしくなっています.

y 座標のデータを計算する部分も, 最初に見出しが存在する場合は先頭に `0` を挿入するように修正する必要があるようです.

**Comment by fukuchancat** [comment]
見出しの座標ですが、文頭の見出しであってもpaddingやmarginのぶん上端からは少し下がった位置に表示されるため0にはなりません(現状のQiitaでは10)。

したがって要素の対応は合っていたのですが、それでも同期がずれていた原因としてはプレビューの親要素に以前は`position: relative;`が指定されていた?のが消えているために各見出しの[offsetTop](https://developer.mozilla.org/ja/docs/Web/API/HTMLElement/offsetTop)の値が正常に計算されていなかったようです。
